<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MigaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BreadcrumbRepository extends EntityRepository {

    /**
     * Inserta o editael registro en la tabla publicacion
     *
     * @author Jose Maria Casado
     *
     * @param array $breadcrumb objeto
     *
     * @return boolean
     * @throws \Exception
     */
    public function saveBreadcrumb($breadcrumb)
    {
        $em = $this->getEntityManager();

        $em->persist($breadcrumb);
        $em->flush();

        return true;
    }

    /**
     * Borra la miga que le pasamos como parametro
     *
     * @author Jose Maria Casado
     *
     * @param Breadcrumb $breadcrumb Miga
     *
     * @return boolean $wasSuccessful
     */
    public function eraseBreadcrumb($breadcrumbs)
    {
        $em = $this->getEntityManager();

        foreach ($breadcrumbs as $breadcrumb) {
            $em->remove($breadcrumb);
        }
        $em->flush();

        return true;
    }
}
