<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;
use App\Entity;
/**
 * NodesBreadcrumbsRelationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NodesBreadcrumbsRelationRepository extends EntityRepository {


    /**
     * Borra todos los elementos de la tabla que le pasamos como parametro
     *
     * @author Jose Maria Casado
     *
     * @param array $elements listado de los registros a eliminar
     *
     * @return boolean $wasSuccessful
     */
    public function eraseBreadcrumbRelationsBd($elements)
    {
        foreach ($elements as $element) {
            $this->getEntityManager()->remove($element);
        }
        $this->getEntityManager()->flush();

        return true;
    }


    /**
     * Inserta un nuevo registro en la tabla de relaciones de nodos.
     *
     * @author Jose Maria Casado
     *
     * @param array $listaNodos listado de los nodos de la miga
     * @param integer $idPublicacion id de la publicacion
     *
     * @return boolean
     * @throws \Exception
     */
    public function saveBreadcrumbRelationsBd($idPublicacion, $listaNodos)
    {
        $em = $this->getEntityManager();

        try {
            foreach ($listaNodos as $nodo) {
                $breadcrumbRelation = new Entity\NodesBreadcrumbsRelation();
                $breadcrumbRelation->setIdNodo($nodo['ID']);
                $breadcrumbRelation->setIdPublicacion($idPublicacion);

                $em->persist($breadcrumbRelation);
            }

            $em->flush();

        } catch (\Exception $e) {
            throw new \Exception(
                'Ha ocurrido un error al insertar una relacion de nodo y miga'
            );
        }

        return true;
    }

    /**
     * Comprueba si un nodo pertenece a una miga
     *
     * @author Jose Maria Casado
     *
     * @param string $id Id del nodo
     *
     * @return boolean Si Pertenece a alguna miga
     */
    public function breadcrumbsId($id)
    {
        $qb = $this->createQueryBuilder('NodesBreadcrumbsRelation');
        $qb->select('t')
           ->from('UEdit\Bundle\NavigationBundle\Entity\NodesBreadcrumbsRelation', 't')
           ->where('t.idNodo = :idNodo')
           ->setParameter('idNodo', $id);

        $relations = $qb->getQuery()->execute();

        return $relations;
    }

}
